=== 0x6b7966/attackTreeDraw/attackTreeDraw/fileHandler/assets/attackTreeSimple.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Simple element declarations -->
    <xs:element name="title" type="xs:string"/>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="date" type="xs:date"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="root" type="xs:IDREF"/>

    <!-- Complex element declarations -->
    <xs:element name="attribute">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="key" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- Attribute declaration -->
    <xs:attribute name="id">
        <xs:simpleType>
            <xs:restriction base="xs:ID">
                <xs:pattern value="N[0-9]{4}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="meta">
        <xs:complexType>
            <xs:all>
                <xs:element ref="title"/>
                <xs:element ref="author"/>
                <xs:element ref="date" minOccurs="0"/>
                <xs:element ref="description" minOccurs="0"/>
                <xs:element ref="root" minOccurs="0"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:group name="threatChoiceGroup">
        <xs:choice>
            <xs:element name="alternative">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="threat" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="threatChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="composition">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="threat" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="threatChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="sequence">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="threat" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="threatChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="threshold">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="threat" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="threatChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>

    <xs:group name="countermeasureChoiceGroup">
        <xs:choice>
            <xs:element name="alternative">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="countermeasure" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="countermeasureChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="composition">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="countermeasure" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="countermeasureChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="sequence">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="countermeasure" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="countermeasureChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="threshold">
                <xs:complexType>
                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element ref="countermeasure" minOccurs="0" maxOccurs="unbounded"/>
                        <xs:group ref="countermeasureChoiceGroup" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:choice>
                    <xs:attribute ref="id" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>

    <xs:element name="countermeasure">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="description"/>
                <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="subtree" minOccurs="0">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element ref="countermeasure"/>
                            <xs:group ref="countermeasureChoiceGroup"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="threat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="description"/>
                <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="subtree" minOccurs="0">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element ref="threat"/>
                            <xs:group ref="threatChoiceGroup"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="countermeasures" minOccurs="0">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element ref="countermeasure"/>
                            <xs:group ref="countermeasureChoiceGroup"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="tree">
        <xs:complexType>
            <xs:all>
                <xs:element ref="threat"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="attackTree">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="meta"/>
                <xs:element ref="tree"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0x6b7966/attackTreeDraw/docs/xml/exampleTreeSimple.xml
<?xml version="1.0" encoding="UTF-8"?>
<attackTree
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns=""
        xsi:noNamespaceSchemaLocation="attackTreeSimple.xsd">
    <meta>
        <title>Attack on an Web Server</title>
        <author>Daniel Fischer</author>
        <date>2017-11-19</date>
        <description>Example attack on an web server</description>
    </meta>
    <tree>
        <threat id="N0001">
            <title>Attack on web server</title>
            <description>attacking an web server</description>
            <subtree>
                <alternative id="N1001">
                    <threat id="N0002">
                        <title>Social Engineering</title>
                        <description>Get password through social engineering</description>
                        <subtree>
                            <alternative id="N1002">
                                <threat id="N0003">
                                    <title>Spear-Phishing attack</title>
                                    <description>execute a spear-phishing attack</description>
                                    <attribute key="difficulty">5.5</attribute>
                                </threat>
                                <threat id="N0004">
                                    <title>Job Interview attack</title>
                                    <description>Do a job interview and get information</description>
                                    <attribute key="difficulty">8</attribute>
                                </threat>
                                <composition id="N1003">
                                    <threat id="N0011">
                                        <title>Test</title>
                                        <description>Test</description>
                                    </threat>
                                    <threat id="N0012">
                                        <title>Test</title>
                                        <description>Test</description>
                                    </threat>
                                </composition>
                            </alternative>
                        </subtree>
                        <countermeasures>
                            <countermeasure id="N0005">
                                <title>Bla</title>
                                <description>Bla</description>
                            </countermeasure>
                        </countermeasures>
                    </threat>
                    <threat id="N0006">
                        <title>Password Brute-Force</title>
                        <description>Brute-forcing the password</description>
                        <attribute key="difficulty">3</attribute>
                        <countermeasures>
                            <composition id="N1006">
                                <countermeasure id="N0007">
                                    <title>Long password</title>
                                    <description>Set a long password</description>
                                    <attribute key="difficulty">1</attribute>
                                </countermeasure>
                                <countermeasure id="N0008">
                                    <title>Brute-Force protection</title>
                                    <description>set brute force protection</description>
                                    <attribute key="difficulty">6</attribute>
                                    <subtree>
                                        <composition id="N1007">
                                            <countermeasure id="N0009">
                                                <title>BlubAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</title>
                                                <description>Bla</description>
                                            </countermeasure>
                                        </composition>
                                    </subtree>
                                </countermeasure>
                            </composition>
                        </countermeasures>
                    </threat>
                </alternative>
            </subtree>
            <countermeasures>
                <countermeasure id="N0010">
                    <title>Secure Webserver</title>
                    <description>Do stuff</description>
                </countermeasure>
            </countermeasures>
        </threat>
    </tree>
</attackTree>
