=== 0x6b7966/attackTreeDraw/doc/xml/attackTreeExtended.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Simple element declarations -->
    <xs:element name="title" type="xs:string"/>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="date" type="xs:date"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="name" type="xs:string"/>

    <!-- Simple attribute declarations -->
    <xs:element name="attribute">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="key" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="alternative|composition|sequence"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="attackTree">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="meta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element ref="author"/>
                            <xs:element ref="date"/>
                            <xs:element ref="description"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="threats">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="threat" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="T[0-9]{4}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="countermeasures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="countermeasure" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="C[0-9]{4}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="connections">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="connection" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="to" type="xs:IDREF" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute  name="from" type="xs:IDREF" use="required"/>
                                    <xs:attribute ref="type" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 0x6b7966/attackTreeDraw/doc/xml/exampleTreeExtended.xml
<?xml version="1.0" encoding="UTF-8"?>
<attackTree
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns=""
        xsi:noNamespaceSchemaLocation="attackTreeExtended.xsd">
    <meta>
        <title>Web-Server attack</title>
        <author>Daniel Fischer</author>
        <date>2017-11-13</date>
        <description>This tree visualises the attack on an Web Server</description>
        <root>N0000</root>
    </meta>
    <threats>
        <threat id="N0000">
            <title>Web-Server attack</title>
            <description>Attack on an Web-Server</description>
        </threat>
        <threat id="N0001">
            <title>Password gathering</title>
            <description>Get the passwords</description>
        </threat>
        <threat id="N0002">
            <title>Brute Forcing</title>
            <description>Brute Forcing the password</description>
        </threat>
        <threat id="N0003">
            <title>Social Engineering the password</title>
            <description>Social Engineering the password</description>
        </threat>
    </threats>
    <countermeasures>
        <countermeasure id="N0004">
            <title>Long Passwords</title>
            <description>Set password length > 20</description>
        </countermeasure>
        <countermeasure id="N0005">
            <title>IDS for password forms</title>
            <description>Set up a IDS to find brute force attempts</description>
        </countermeasure>
        <countermeasure id="N0006">
            <title>Social engineering seminars</title>
            <description>Set up seminars to counter social engineering</description>
        </countermeasure>
    </countermeasures>
    <conjunctions>
        <conjunction type="alternative" id="N1001"/>
        <conjunction type="composition" id="N1002"/>
        <conjunction type="alternative" id="N1003"/>
        <conjunction type="alternative" id="N1004"/>
        <conjunction type="alternative" id="N1005"/>
    </conjunctions>
    <connections>
        <connection source="N0000" destination="N1001"/>
        <connection source="N1001" destination="N0001"/>
        <connection source="N0001" destination="N1002"/>
        <connection source="N1002" destination="N0002"/>
        <connection source="N0001" destination="N1003"/>
        <connection source="N1003" destination="N0004"/>
        <connection source="N1003" destination="N0005"/>
        <connection source="N0002" destination="N1004"/>
        <connection source="N1004" destination="N0003"/>
        <connection source="N0003" destination="N1005"/>
        <connection source="N1005" destination="N0002"/>
    </connections>
</attackTree>
